version: '3.8'

services:
  fantasy-football-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: ff-dashboard-dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - FAST_REFRESH=true
    networks:
      - fantasy-dev-network
    stdin_open: true
    tty: true

networks:
  fantasy-dev-network:
    driver: bridge